### ISSUE TITLE
Tilt (Zwischenposition/Lüftungsposition) no longer available since latest update

### ISSUE THREAD

**Issue by frankfrommelt** [Kannix2005/homeassistant-selve#5] opened 2022-11-08 09:59 UTC
Hi Stefan,
the covers for out sleeping room have been moving to tilt-posion (cover.open_cover_tilt) using your intergration for weeks.
No, since the last update, I get an error "Entity cover.sz_2 does not support this service.".
I have checked all ...tilt... services seem to be no longer available (cover.open_cover_tilt, cover.close_cover_tilt, cover.set_cover_tilt_position, ...).
Best regards
    Frank

**Comment by Julger92** [comment] 2022-11-08 11:23
Hi Frank, what exactly do you mean? I also do nto have the function anymore foe the status.
What did you had previously implemented? Can you share this to me?
I was not able to have exactly what you described...

**Comment by frankfrommelt** [comment] 2022-11-08 11:39
Hi,
over the past weeks I have been using an automation to set the Commeo covers of the sleeping room to "tilt" (Lüftungsposition).

`service: cover.open_cover_tilt
data: {}
target:
  entity_id: cover.sz`

Since the last update I get an error message instead of setting the device to tilt.

Fehler beim Ausführen einer Aktion
Entity cover.sz_2 does not support this service.

Opening and closing the device (or setting it to a certain percentage) still works as before.

But all the services including "tilt" seem to be not available.

I see the following errors in my logfiles:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:51:08 (4 occurrences)
Last logged: 12:31:58

[547967065904] Error handling message: Entity cover.az_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
[547967065904] Error handling message: Entity cover.sz_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
[547502662912] Error handling message: Entity cover.sz_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:409
First occurred: 10:51:08 (4 occurrences)
Last logged: 12:31:58

websocket_api script: Error executing script. Error for call_service at pos 1: Entity cover.az_2 does not support this service.
websocket_api script: Error executing script. Error for call_service at pos 1: Entity cover.sz_2 does not support this service.

Take care

    Frank

**Comment by Kannix2005** [comment] 2022-11-08 11:43
Hi Frank,

Tilting is not implemented yet in this new version. Should be not much work though.
Please wait a little longer.

Best

**Comment by frankfrommelt** [comment] 2022-11-08 11:52
Hi Stefan,

 �

OK, I didn’t see anything about this functionality missing in the current version in the change logs.

 �

I now have set the cover to a certain percentage to “emulate” the tilt setting.

 �

But setting the covers to “tilt” is much easier as this setting is saved in the devices and one does not have to figure out the percentage manually.

 �

I am using “tilt” for sun protection in summertime as well, but I guess this feature will not be missed for the next few months here… 😉

 �

Take care

 �

 � � � � � � � � � � � � � � � � � � � � � Frank 

 �

Von: Stefan Altheimer ***@***.***> 
Gesendet: Dienstag, 8. November 2022 12:44
An: Kannix2005/homeassistant-selve ***@***.***>
Cc: Frank Frommelt ***@***.***>; Author ***@***.***>
Betreff: Re: [Kannix2005/homeassistant-selve] Tilt (Zwischenposition/Lüftungsposition) no longer available since latest update (Issue #5)

 �

Hi Frank,

Tilting is not implemented yet in this new version. Should be not much work though.
Please wait a little longer.

Best

**Comment by Julger92** [comment] 2022-11-08 12:02
> Hi, over the past weeks I have been using an automation to set the Commeo covers of the sleeping room to "tilt" (Lüftungsposition).
> 
> `service: cover.open_cover_tilt data: {} target: entity_id: cover.sz`
> 
> Since the last update I get an error message instead of setting the device to tilt.
> 
> Fehler beim Ausführen einer Aktion Entity cover.sz_2 does not support this service.
> 
> Opening and closing the device (or setting it to a certain percentage) still works as before.
> 
> But all the services including "tilt" seem to be not available.
> 
> I see the following errors in my logfiles:
> 
> Logger: homeassistant.components.websocket_api.http.connection Source: components/websocket_api/connection.py:150 Integration: Home Assistant WebSocket API (documentation, issues) First occurred: 10:51:08 (4 occurrences) Last logged: 12:31:58
> 
> [547967065904] Error handling message: Entity cover.az_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36) [547967065904] Error handling message: Entity cover.sz_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36) [547502662912] Error handling message: Entity cover.sz_2 does not support this service. (unknown_error) from 192.168.1.144 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
> 
> Logger: homeassistant.helpers.script.websocket_api_script Source: helpers/script.py:409 First occurred: 10:51:08 (4 occurrences) Last logged: 12:31:58
> 
> websocket_api script: Error executing script. Error for call_service at pos 1: Entity cover.az_2 does not support this service. websocket_api script: Error executing script. Error for call_service at pos 1: Entity cover.sz_2 does not support this service.
> 
> Take care
> 
> ```
> Frank
> ```

Do you sue COMEO or IVEO? I was never able to make percentage runs :(

**Comment by Kannix2005** [comment] 2022-12-21 11:28
Can you check with the new version if it works as intended?

**Comment by frankfrommelt** [comment] 2023-01-10 14:16
Hi Stefan,

 �

sorry for the late reply, but I was out for vacation for a loooong time….

 �

Basically, it now works as expected, but one thing is a bit strange and I do not know if this is coming from hacs or your integration:

 �

The two Open and Close Buttons and the the Kippstellung/Tilt buttons (and related services) work as expected.


But as you see in the screen shots the “Abdeckung kippend öffnen” or “Abdeckung kippend schließen” Buttons
are only selectable when the cover is not completely closed oder completely opened.

They should be available at any state of the cover as they are only saved intermediated positions of the cover.

 �

What from my perspective is a bit strange (but this is the same in all versions of the integration) is that 

Position 100% represents “open cover” and position 0% is “closed cover”.

I had expected it to be exactly the other way around: 100% should be “closed” and 0% should be “open”.

 �



 �



 �



 �

Take care

 �

 � � � � � � � � � � � � � � � � � � � � � Frank 

 �

Von: Stefan Altheimer ***@***.***> 
Gesendet: Mittwoch, 21. Dezember 2022 12:29
An: Kannix2005/homeassistant-selve ***@***.***>
Cc: Frank Frommelt ***@***.***>; Author ***@***.***>
Betreff: Re: [Kannix2005/homeassistant-selve] Tilt (Zwischenposition/Lüftungsposition) no longer available since latest update (Issue #5)

 �

Can you check with the new version if it works as intended?

**Comment by Kannix2005** [comment] 2023-02-10 14:00
The buttons should now be always accessible.
I added an option to reverse the direction of the covers. Though it may not work for now - don´t know why though. You can try though.
I´m closing this issue because the core problem has been solved.

**Closed by Kannix2005** 2023-02-10 14:00 UTC

**Comment by Deinjo** [comment] 2023-11-16 19:25
Hello.
I have just installed 3.0.6-1. The Tilt service does not seem to be available for my 6 Iveo shutters.

Is this a bug or will the function be available sometimes?
